# fly.toml app configuration file generated for snakes-and-ladders-modified on 2025-03-23T21:05:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'snakes-and-ladders-modified'
primary_region = 'cdg'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
